### ISSUE TITLE
Come ottenere più risultati?

### ISSUE THREAD

**Issue by aleeeee1** [madbob/gtt-pirate-api#1]
Come faccio ad ottenere più risultati? In alcune fermate l'output è di una decina di orari in altre anche meno di 5.

**Comment by madbob** [comment]
Ahime', quelli sono tutti i dati estrapolati dal sito originale di 5T. Evidentemente anche loro fanno previsioni solo entro un determinato periodo, a seconda della linea e della fermata.

**Comment by madbob** [comment]
Con la nuova implementazione (cfr #3 ) pesco i dati per le prossime 2 ore.

In verità comunque li metto in una cache e faccio una nuova richiesta quando questi risultati sono esauriti (ovvero: dopo altre 2 ore), se fosse necessario potrei introdurre un qualche parametro per avere sempre i dati in tempo reale (ma dovrei introdurre un throttling, altrimenti GTT mangia la foglia e mi banna l'IP...).
