### ISSUE TITLE
ritorna lista vuota?

### ISSUE THREAD

**Issue by fily1212** [madbob/gtt-pirate-api#3]
Ciao, 
credo che ci sia un problema perché la risorsa ritorna la lista vuota. Non so se succede anche a te o sbaglio qualcosa io... 

A presto,

**Comment by madbob** [comment]
Mi sa che hanno soppresso l'endpoint cui mi agganciavo per recuperare le informazioni...
Sto cercando una alternativa, ce ne sono diverse (tutte ovviamente non pubbliche e di cui dover fare reverse engineering...), vedo di implementarne una.

**Comment by madbob** [comment]
Ok, in questo commit https://github.com/madbob/gtt-pirate-api/commit/ab2672a2904b2fe138db037a566ab5052df2b6ba ho reimplementato praticamente tutto daccapo per utilizzare un diverso endpoint.
Grazie della segnalazione!

**Comment by fily1212** [comment]
Gra

**Comment by fily1212** [comment]
Grazie mille! una domanda: https://gpa.madbob.org/query.php?stop=966 così funziona, ma mettendolo dentro una fetch in js 
(per esempio 
`fetch('https://gpa.madbob.org/query.php?stop=966')
  .then(response => response.json())
  .then(passaggi =>{ console.log(passaggi) });`
) 

ottengo questo errore nel console log: Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da https://gpa.madbob.org/query.php?stop=966. Motivo: header CORS “Access-Control-Allow-Origin” mancante. Codice di stato: 200. 

Forse manca un parametro nel server? 
Ti dico anche dove la sto utilizzando: sto insegnando javascript a degli studenti e mi piacerebbe portare come esercizio la costruzione di una pagina che chiama la tua risorsa e poi mostra i passaggi. Quindi la risorsa verrà utilizzata per qualche giorno ma non dovrebbe avere il volume per buttarti giù il server :) 

grazie ancora!

**Comment by madbob** [comment]
Hai ragione, non avevo abilitato gli headers CORS. Fatto adesso.
Se dovessi avere ancora dei problemi (o avessi delle richieste) non esitare a scrivere.

**Comment by fily1212** [comment]
Ciao, 
sto insegnando di nuovo agli studenti dell'anno successivo come funzionano le fetch. Volevo di nuovo utilizzare la tua bellissima API, il problema è che ho di nuovo l'errore del Access-Control-Allow-Origin, questa volta con codice errore 301. Potrebbe essere che sia di nuovo da abilitare? 
grazie
