### ISSUE TITLE
Resulting JSON returns missing characters on some special lines

### ISSUE THREAD

**Issue by ozkut** [madbob/gtt-pirate-api#5]
On certain lines like 16 or 58 / the resulting JSON returns missing characters for the names of said lines. For example on stop 610, the resulting output contains `[{"line":"16","hour":"20:12:02","realtime":"true"}]`. Here, the problem is that the 'CD' after 16 is sometimes missing and sometimes not. The same happens for 58 / on stop 1944. Sometimes it returns `[{"line":"58 \/","hour":"20:15:51","realtime":true}]` but sometimes it returns `[{"line":"58","hour":"20:15:51","realtime":true}]` where the / is missing.  These issues aren't stop specific from what I can tell, I just used them for testing.

**Comment by madbob** [comment]
16 are two different lines: 16CD (circolare destra) and 16CS (circolare sinistra).
https://www.gtt.to.it/cms/percorari/urbano?view=percorsi&bacino=U&linea=16CD&Regol=GE
https://www.gtt.to.it/cms/percorari/urbano?view=percorsi&bacino=U&linea=16CS&Regol=GE

Also 58 and 58/ (spelled as "cinquantotto" and "cinquantotto barrato") are two different lines.
https://www.gtt.to.it/cms/percorari/urbano?view=percorsi&bacino=U&linea=58&Regol=GE
https://www.gtt.to.it/cms/percorari/urbano?view=percorsi&bacino=U&linea=58B&Regol=GE

Here a full list of GTT lines, with all the variations.
https://www.gtt.to.it/cms/percorari/urbano

**Comment by ozkut** [comment]
Yes, that is the problem I'm having. On some stops where there are both 58 and 58 / (like 376), somethimes they both get combined into 58, sometimes they are displayed separately. With 16, sometimes it doesn't display if it's CS or CD, only 16. Sometimes the 58 and 58 / do display seperately, and the CS or CD displays on 16, but it is inconsistent in both cases. I apologise for my poor explanation of the issue the first time.
