### ISSUE TITLE
Bloccata richiesta multiorigine (cross-origin)

### ISSUE THREAD

**Issue by fily1212** [madbob/gtt-pirate-api#6]
Ciao, 
sto insegnando di nuovo agli studenti dell'anno successivo come funzionano le fetch. Volevo di nuovo utilizzare la tua bellissima API, il problema è che ho di nuovo l'errore del Access-Control-Allow-Origin, questa volta con codice errore 301. Potrebbe essere che sia di nuovo da abilitare? 
grazie

Errore:
Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da http://gpa.madbob.org/query.php?stop=452. Motivo: header CORS “Access-Control-Allow-Origin” mancante. Codice di stato: 301.

_Originally posted by @fily1212 in https://github.com/madbob/gtt-pirate-api/issues/3#issuecomment-2137413740_

**Comment by madbob** [comment]
Mmm... Ho provato con il seguente banale frammento di HTML a fare una richiesta Ajax da un altro dominio, e funziona.

```
<html>
<body>
        <script>
        fetch('https://gpa.madbob.org/query.php?stop=966')
                .then(response => response.json())
                .then(passaggi => {
                        console.log(passaggi)
                });
        </script>
</body>
</html>
```

![Screenshot-20240529154353-1920x1080](https://github.com/madbob/gtt-pirate-api/assets/166089/26f6f269-b26a-4e84-bef2-043742ad3363)

Cosa mostra il tuo browser tra gli headers della risposta?

**Comment by fily1212** [comment]
![immagine](https://github.com/madbob/gtt-pirate-api/assets/10487430/d9d81acf-5a7f-4f7d-97ce-8ebdb2f3304b)

    fetch("http://gpa.madbob.org/query.php?stop="+numeroFermata)
        .then(response => {
      mostraOrario(response);
   })

**Comment by madbob** [comment]
Ok, ho capito: facendo la richiesta in HTTP, e non in HTTPS, faceva un redirect verso la versione HTTPS ma senza aggiungere l'header CORS. Adesso aggiunge l'header anche nella versione HTTP.
